# vim: set ft=ansible:
- hosts: ec2postgresql
  gather_facts: false
  user: ubuntu
  tasks:
    - name: Template Postgresql configuration file
      become: yes
      action: template
        src=templates/confs/{{ item }}.conf.j2
        dest=/etc/postgresql/9.6/main/{{ item }}.conf
      with_items:
        - pg_hba
        - postgresql
      notify:
        - restart postgresql
      when: postgres_from_deb is defined

    - name: Template Postgresql configuration file
      become: yes
      become_user: postgres
      action: template
        src=templates/confs/{{ item.source }}.conf.j2
        dest=/home/postgres/build/data/{{ item.target }}.conf
      with_items:
        - { source: "pg_hba", target: "pg_hba"}
        - { source: "postgresql_from_source", target: "postgresql" }
      when: postgres_from_source is defined

    - name: restart postgresql
      become: yes
      become_user: postgres
      shell: ./bin/pg_ctl -D data restart chdir=/home/postgres/build/
      when: postgres_from_source is defined

    - meta: flush_handlers

    - name: Copy init sql
      template:
        src=templates/init/pg_init.sql
        dest=/home/ubuntu/pg_init.sql
      when: postgres_from_deb is defined

    - name: Create usertable with jsonb
      shell: psql ycsb -U {{ db_user }} < /home/ubuntu/pg_init.sql
      when: postgres_from_deb is defined

    - name: Copy init sql
      template:
        src=templates/init/pg_init.sql
        dest=/home/postgres/pg_init.sql
      become: yes
      become_user: postgres
      when: postgres_from_source is defined

    - name: Create usertable with jsonb
      shell: psql -h /var/run/postgresql ycsb -U {{ db_user }} < /home/postgres/pg_init.sql
      become: yes
      become_user: postgres
      environment:
        PATH: $PATH:/home/postgres/build/bin
      when: postgres_from_source is defined

    - name: Start pg_view
      shell: pg_view -o json > /tmp/postgresql.json &
      become: yes
      become_user: postgres
      register: pg_view_start

  environment:
    PGPASSWORD: "{{ db_pass }}"

  handlers:
    - name: restart postgresql
      become: yes
      service:
        name=postgresql
        state=restarted
